"""Small protocol seams for replaceable external services.

Adapters remain responsible for translating these domain-level ports to yt-dlp,
mpv, or local JSON.  The ASR contract already lives in ``voiceyt.asr.base``
and is intentionally not duplicated here.
"""

from __future__ import annotations

from typing import Mapping, Protocol, runtime_checkable

from .domain import PlaybackEvent, Track


@runtime_checkable
class SearchPort(Protocol):
    def search(self, query: str, music_only: bool = False) -> tuple[Track, ...]: ...

    def resolve(self, track: Track) -> tuple[str, Mapping[str, str]]: ...


@runtime_checkable
class PlayerPort(Protocol):
    def play_queue(self, tracks: tuple[Track, ...], start_index: int = 0) -> None: ...

    def next_track(self) -> bool: ...

    def prev_track(self) -> bool: ...

    def jump_to(self, index: int) -> bool: ...

    def pause(self) -> bool: ...

    def unpause(self) -> bool: ...

    def stop(self) -> bool: ...

    def seek(self, seconds: float) -> bool: ...

    def volume(self) -> float: ...

    def set_volume(self, value: float) -> float: ...

    def snapshot(self) -> PlaybackEvent: ...


@runtime_checkable
class PlaylistPort(Protocol):
    def names(self) -> list[str]: ...

    def tracks(self, name: str) -> list[dict]: ...

    def create(self, name: str) -> None: ...

    def rename(self, old: str, new: str) -> None: ...

    def delete(self, name: str) -> None: ...

    def add(self, name: str, title: str, url: str) -> None: ...

    def remove(self, name: str, index: int) -> None: ...

    def reorder(self, name: str, index: int, new_index: int) -> None: ...


__all__ = ["SearchPort", "PlayerPort", "PlaylistPort"]
